#' Minimal functions for basic plotting of groupwise comparisons.
#'
#' These functions are designed to be called by \code{\link{build_plots}}
#' as part of the flyover workflow, but can also be used as standalone plotting
#' utilities.  Each function has identical arguments, but each will produce
#' a different visual comparison of data across groups depeding on the
#' data type to be compared and the geom selected.  The output
#' can by modified by directly adding \code{ggplot2} layers in the usual way.

#' @param tbl A \code{tibble} containing the variable of interest and the grouping variable.
#' @param var Character string; the variable name whose distribution is of interest.
#' @param group_var Character string; the variable name defining different groups.
#' 
#' @return A plot object generated by the \code{ggplot2} package.
#' 
#' @export
#'
flyover_histogram <- function(tbl, var, group_var) {
  ggplot(tbl, aes_string(x = var, fill = group_var)) +
    geom_histogram(position = "identity", alpha = 0.5) +
    scale_fill_discrete(name = "Group") +
    theme_minimal(base_size = 14)
}


#' @rdname flyover_histogram
#' @export
flyover_density <- function(tbl, var, group_var) {
  ggplot(tbl, aes_string(x = var, fill = group_var)) +
    geom_density(position = "identity", alpha = 0.5) +
    scale_fill_discrete(name = "Group") +
    theme_minimal(base_size = 14)
}