#' Minimal functions for basic plotting of groupwise comparisons.
#'
#' These functions are designed to be called by \code{\link{build_plots}}
#' as part of the flyover workflow, but can also be used as standalone plotting
#' utilities.  Each function has identical arguments, but each will produce
#' a different visual comparison of data across groups depeding on the
#' data type to be compared and the geom selected.  The output
#' can by modified by directly adding \code{ggplot2} layers in the usual way.

#' @param tbl A \code{tibble} containing the variable of interest and the grouping variable.
#' @param var Character string; the variable name whose distribution is of interest.
#' @param group_var Character string; the variable name defining different groups.
#' 
#' @return A plot object generated by the \code{ggplot2} package.
#' 
#' @examples
#' \dontrun{
#' x <- tibble::tibble(group = rep(c("old", "new"), each = 100),
#'                     rand  = c(rnorm(100), rnorm(100, mean = 1)))
#' flyover_histogram(x, "rand", "group")
#' 
#' y <- tibble::tibble(group = rep(c("old", "new"), each = 100),
#'                     rand  = sample(letters[1:4], 200, replace = TRUE))
#' flyover_bar_fill(y, "rand", "group")
#' }
#' 
#' @export
#'
flyover_histogram <- function(tbl, var, group_var) {
  ggplot(tbl, aes_string(x = var, fill = group_var)) +
    geom_histogram(position = "identity", alpha = 0.5) +
    scale_fill_discrete(name = "Group") +
    theme_minimal(base_size = 14)
}


#' @rdname flyover_histogram
#' @export
flyover_density <- function(tbl, var, group_var) {
  ggplot(tbl, aes_string(x = var, fill = group_var)) +
    geom_density(position = "identity", alpha = 0.5) +
    scale_fill_discrete(name = "Group") +
    theme_minimal(base_size = 14)
}


#' @rdname flyover_histogram
#' @export
flyover_binline <- function(tbl, var, group_var) {
  ggplot(tbl, aes_string(x = var, y = group_var)) +
    geom_density_ridges(stat = "binline", bins = 30, scale = 0.95, draw_baseline = FALSE) +
    theme_minimal(base_size = 14)
}


#' @rdname flyover_histogram
#' @export
flyover_bar_dodge <- function(tbl, var, group_var) {
  ggplot(tbl, aes_string(y = var, fill = group_var)) +
    geom_bar(position = position_dodge()) +
    theme_minimal(base_size = 14) + 
    theme(legend.position = "top")
}


#' @rdname flyover_histogram
#' @export
flyover_bar_fill <- function(tbl, var, group_var) {
  ggplot(tbl, aes_string(y = var, fill = group_var)) +
    geom_bar(position = position_fill(reverse = TRUE)) +
    theme_minimal(base_size = 14) +
    theme(legend.position = "top") +
    labs(x = "proportion")
}