#' Minimal functions for basic plotting of groupwise comparisons.
#'
#' These functions are designed to be called by \code{\link{build_plots}}
#' as part of the flyover workflow, but can also be used as standalone plotting
#' utilities.  Each function has identical arguments, but each will produce
#' a different visual comparison of data across groups depeding on the
#' data type to be compared and the geom selected.  The output
#' can by modified by directly adding \code{ggplot2} layers in the usual way.

#' @param tbl A \code{tibble} containing the variable of interest and the grouping variable.
#' @param var Character string; the variable name whose distribution is of interest.
#' @param group_var Character string; the variable name defining different groups.
#' @param ... Additional arguments to pass to the \code{geom} of the
#'            supplied \code{flyover} plot function.
#' 
#' @return A plot object generated by the \code{ggplot2} package.
#' 
#' @examples
#' \dontrun{
#' x <- tibble::tibble(group = rep(c("old", "new"), each = 100),
#'                     rand  = c(rnorm(100), rnorm(100, mean = 1)))
#' flyover_histogram(x, "rand", "group")
#' 
#' y <- tibble::tibble(group = rep(c("old", "new"), each = 100),
#'                     rand  = sample(letters[1:4], 200, replace = TRUE))
#' flyover_bar_fill(y, "rand", "group")
#' }
#' 
#' @export
flyover_histogram <- function(tbl, var, group_var, ...) {
  ggplot(tbl, aes_string(x = var, fill = group_var)) +
    geom_histogram(position = "identity", alpha = 0.5, ...) +
    theme_minimal(base_size = 14)
}


#' @rdname flyover_histogram
#' @export
flyover_density <- function(tbl, var, group_var, ...) {
  ggplot(tbl, aes_string(x = var, fill = group_var)) +
    geom_density(position = "identity", alpha = 0.5, ...) +
    theme_minimal(base_size = 14)
}


#' @rdname flyover_histogram
#' @export
flyover_binline_ridges <- function(tbl, var, group_var, ...) {
  ggplot(tbl, aes_string(x = var, y = group_var)) +
    ggridges::geom_density_ridges(stat = "binline", bins = 30, scale = 0.95, draw_baseline = FALSE, ...) +
    theme_minimal(base_size = 14)
}


#' @rdname flyover_histogram
#' @export
flyover_density_ridges <- function(tbl, var, group_var, ...) {
  ggplot(tbl, aes_string(x = var, y = group_var)) +
    ggridges::geom_density_ridges(...) +
    theme_minimal(base_size = 14)
}


#' @rdname flyover_histogram
#' @export
flyover_bar_dodge <- function(tbl, var, group_var, ...) {
  ggplot(tbl, aes_string(y = group_var, fill = var)) +
    geom_bar(position = position_dodge(), ...) +
    theme_minimal(base_size = 12) + 
    theme(legend.position = "top")
}


#' @rdname flyover_histogram
#' @export
flyover_bar_fill <- function(tbl, var, group_var, ...) {
  ggplot(tbl, aes_string(y = group_var, fill = var)) +
    geom_bar(position = position_fill(reverse = TRUE), ...) +
    theme_minimal(base_size = 12) +
    theme(legend.position = "top") +
    labs(x = "proportion")
}


#' @rdname flyover_histogram
#' @export
flyover_na_percent <- function(tbl, var, group_var, ...) {
  tbl_grp <- dplyr::group_by_at(tbl, group_var)
  summary <- dplyr::summarize_at(tbl_grp, vars(var), flyover:::percent_na)

  ggplot(summary, aes_string(x = group_var, y = var, group = 1)) +
    geom_point(stat = "summary", fun = sum) +
    geom_line(stat = "summary", fun = sum, ...) +
    theme_minimal(base_size = 14) +
    scale_y_continuous(limits = c(0, 100)) +
    labs(x = group_var, y = "Percent NA")
}


#' @rdname flyover_histogram
#' @export
flyover_na_count <- function(tbl, var, group_var, ...) {
  tbl_grp <- dplyr::group_by_at(tbl, group_var)
  summary <- dplyr::summarize_at(tbl_grp, vars(var), flyover:::count_na)

  ggplot(summary, aes_string(x = group_var, y = var, group = 1)) +
    geom_point(stat = "summary", fun = sum) +
    geom_line(stat = "summary", fun = sum) +
    theme_minimal(base_size = 14) +
    ylim(0, max(summary[[var]])) +
    labs(x = group_var, y = "Count of NA")
}