#' Create overlaid smooth densities of a numeric column grouped by a specified variable.
#' 
#' @description This function is designed to be called by \code{\link{build_plots}}
#'              but is exported for convenience so the user can test the output.
#'              The function builds a somewhat opinionated density plot in which
#'              distributions can be visually compared across groups.
#'              It is recommended that no more than three groups be compared
#'              with this function to avoid visual clutter.
#'              
#' @param tbl A \code{tibble} containing the variable of interest and the grouping variable.
#' @param var Character string; the numeric variable whose distribution is of interest
#' @param group_var Character string; the variable defining different groups.
#' 
#' @return A plot object generated by the \code{ggplot2} package.
#' @examples
#' \dontrun{
#' x <- tibble::tibble(group = rep(c("old", "new"), each = 1000),
#'                     rand  = c(rnorm(1000), rnorm(1000, mean = 1)))
#' flyover_density(x, "rand", "group")
#' }
#' 
#' @export


flyover_density <- function(tbl, var, group_var) {
  ggplot(tbl, aes_string(x = var, fill = group_var)) +
    geom_density(position = "identity", alpha = 0.5) +
    scale_fill_discrete(name = "Group") +
    theme_minimal(base_size = 14)
}